FROM python:3.7.3-alpine3.9

WORKDIR /app

RUN pip install --upgrade pip

RUN apk --no-cache update && \
  apk --no-cache add musl-dev gcc nodejs nodejs-npm jq && \
  pip --no-cache-dir install awscli && \
  rm -rf /var/cache/apk/* && \
  npm install -g npm@6.9.0 \
  npm install -g serverless