export const CONFIG = {
  PORT: () => parseInt(process.env.PORT || "3000", 10),
  DATABASE_URL: () => process.env.DATABASE_URL,
  DATABASE_NAME: () => process.env.DATABASE_NAME,
  AWS_REGION: () => process.env.AWS_REGION,
  LALAMOVE_SDK_ENV: () => process.env.LALAMOVE_SDK_ENV,
  LALAMOVE_API_KEY: () => process.env.LALAMOVE_API_KEY,
  LALAMOVE_API_SECRET: () => process.env.LALAMOVE_API_SECRET,
  LALAMOVE_API_BASE_URL: () => process.env.LALAMOVE_API_BASE_URL,
  LALAMOVE_API_GET_QUOTATION_ROUTE: () =>
    process.env.LALAMOVE_API_GET_QUOTATION_ROUTE,
  LALAMOVE_API_PLACE_ORDER_ROUTE: () =>
    process.env.LALAMOVE_API_PLACE_ORDER_ROUTE,
  LALAMOVE_API_EDIT_ORDER_ROUTE: () =>
    process.env.LALAMOVE_API_EDIT_ORDER_ROUTE,
  LALAMOVE_API_CANCEL_ORDER_ROUTE: () =>
    process.env.LALAMOVE_API_CANCEL_ORDER_ROUTE,
  LALAMOVE_API_ORDER_DETAILS_ROUTE: () =>
    process.env.LALAMOVE_API_ORDER_DETAILS_ROUTE,
  LALAMOVE_API_DRIVER_DETAILS_ROUTE: () =>
    process.env.LALAMOVE_API_DRIVER_DETAILS_ROUTE,
  CRMZ_ACCESS_TOKEN_URL: () => process.env.CRMZ_ACCESS_TOKEN_URL,
  CRMZ_ACCESS_TOKEN_USERNAME: () => process.env.CRMZ_ACCESS_TOKEN_USERNAME,
  CRMZ_ACCESS_TOKEN_PASSWORD: () => process.env.CRMZ_ACCESS_TOKEN_PASSWORD,
  CRMZ_CLAIMS_BASE_URL: () => process.env.CRMZ_CLAIMS_BASE_URL,
  CRMZ_CLAIMS_UPDATE_DELIVERY_STATUS_ROUTE: () =>
    process.env.CRMZ_CLAIMS_UPDATE_DELIVERY_STATUS_ROUTE,
  WEBHOOK_MESSAGE_PROCESSOR_QUEUE: () =>
    process.env.WEBHOOK_MESSAGE_PROCESSOR_QUEUE,
  LOGISTICS_FE_TRACKING_PAGE: () => process.env.LOGISTICS_FE_TRACKING_PAGE,
  GOOGLE_API_KEY: () => process.env.GOOGLE_API_KEY,
  GEOCODING_BASE_URL: () => process.env.GEOCODING_BASE_URL,
  WEBHOOK_ENDPOINT: () => process.env.WEBHOOK_ENDPOINT,
  SLACK_CHANNEL_URL: () => process.env.SLACK_CHANNEL_URL,
  AUTH_KEYCLOAK_URL: () => process.env.AUTH_KEYCLOAK_URL,
  AUTH_TENANT_ID: () => process.env.AUTH_TENANT_ID,
  AUTH_COUNTRY_CODE: () => process.env.AUTH_COUNTRY_CODE,
  AUTH_GRANT_TYPE_PASSWORD: () => process.env.AUTH_GRANT_TYPE_PASSWORD,
  AUTH_GRANT_TYPE_REFRESH_TOKEN: () =>
    process.env.AUTH_GRANT_TYPE_REFRESH_TOKEN,
  AUTH_CLIENT_ID: () => process.env.AUTH_CLIENT_ID,
  AUTH_CLIENT_SECRET: () => process.env.AUTH_CLIENT_SECRET,
  LALAMOVE_SERVICE_TYPE: () => process.env.LALAMOVE_SERVICE_TYPE,
  LALAMOVE_SPECIAL_REQUESTS: () => process.env.LALAMOVE_SPECIAL_REQUESTS,
  CRMZ_CLAIMS_UPDATE_DELIVERY_STATUS_QUEUE: () =>
    process.env.CRMZ_CLAIMS_UPDATE_DELIVERY_STATUS_QUEUE,
  BORZO_API_BASE_URL: () =>
    process.env.BORZO_API_BASE_URL ||
    "https://robotapitest-id.borzodelivery.com/api/business/1.3",
  BORZO_API_CREATE_ORDER_ROUTE: () =>
    process.env.BORZO_API_CREATE_ORDER_ROUTE || "/create-order",
  BORZO_API_KEY: () =>
    process.env.BORZO_API_KEY ||
    '{"ID":"6F47CB15E73C34809812863058D80445ECE776BD"}',
  BORZO_API_LIST_ORDERS_ROUTE: () =>
    process.env.BORZO_API_LIST_ORDERS_ROUTE || "/orders",
  BORZO_API_CANCEL_ORDER_ROUTE: () =>
    process.env.BORZO_API_CANCEL_ORDER_ROUTE || "/cancel-order",
  BORZO_API_EDIT_ORDER_ROUTE: () =>
    process.env.BORZO_API_EDIT_ORDER_ROUTE || "/edit-order",
  JWT_SECRET: () => process.env.JWT_SECRET,
  BORZO_CALCULATE_ORDER_ROUTE :()=> process.env.BORZO_CALCULATE_ORDER_ROUTE,
  KEYCLOAK_API_LOGIN_ROUTE: () => process.env.KEYCLOAK_API_LOGIN_ROUTE,
  KEYCLOAK_API_USER_DETAILS_ROUTE: () =>
    process.env.KEYCLOAK_API_USER_DETAILS_ROUTE,
  KEYCLOAK_API_RESET_PASSWORD_ROUTE: () =>
    process.env.KEYCLOAK_API_RESET_PASSWORD_ROUTE,
  CRMZ_NOTIFICATIONS_URL: () => process.env.CRMZ_NOTIFICATIONS_URL,
  LOGISTICS_FE_RESET_PASSWORD: () => process.env.LOGISTICS_FE_RESET_PASSWORD,
  BORZO_API_COURIER_INFO_ROUTE: () => process.env.BORZO_API_COURIER_INFO_ROUTE,
  BORZO_CALLBACK_TOKEN: () => process.env.BORZO_CALLBACK_TOKEN,
  RPX_API_BASE_URL: () =>
    process.env.RPX_API_BASE_URL || "https://api.rpx.co.id/api_beta/v3",
  RPX_API_SEND_SHIPMENT_ROUTE: () =>
    process.env.RPX_API_SEND_SHIPMENT_ROUTE || "/sendShipmentData",
  RPX_API_SEND_PICKUP_REQUEST_ROUTE: () =>
    process.env.RPX_API_SEND_PICKUP_REQUEST_ROUTE || "/sendPickupRequest",
  RPX_API_GET_RATES_ROUTE: () =>
    process.env.RPX_API_GET_RATES_ROUTE || "/rates/",
  RPX_GET_TOKEN_API_URL: () =>
    process.env.RPX_GET_TOKEN_API_URL || "https://api.rpx.co.id/api_beta/token",
  RPX_USERNAME: () => process.env.RPX_USERNAME || "demo",
  RPX_PASSWORD: () => process.env.RPX_PASSWORD || "demo",
  RPX_PRIVATE_KEY: () => process.env.RPX_PRIVATE_KEY,
  RPX_ACCOUNT_NUMBER: () => process.env.RPX_ACCOUNT_NUMBER,
  RPX_API_CANCEL_PICKUP_REQUEST_ROUTE: () =>
    process.env.RPX_API_CANCEL_PICKUP_REQUEST_ROUTE || "/voidPickupRequest",
  RPX_API_VOID_SHIPMENT_DATA_ROUTE: () =>
    process.env.RPX_API_VOID_SHIPMENT_DATA_ROUTE || "/voidShipmentData",
  RPX_API_GET_AWB_DETAIl: () =>
    process.env.RPX_API_BASE_URL + process.env.RPX_GET_AWB_DETAIL_PATH,
  RPX_API_GET_TRACKING: () =>
    process.env.RPX_API_BASE_URL + process.env.RPX_TRACKING_PATH
};
